Revert "use desugaring to remove threetenbp"
This reverts commit 8a1282af9b4492637ffbe9af55a36f8d05ab26ec. This was
causing various NoClassDefFoundError with Jackson on API 21. See
https://github.com/FasterXML/jackson-databind/issues/2807.

  FATAL EXCEPTION: main
Process: com.cradleVSA.neptune, PID: 18073
com.fasterxml.jackson.databind.JsonMappingException: Failed on call to
`getDeclaredMethods()` on class `kotlin.collections.EmptyList`, problem:
(java.lang.NoClassDefFoundError) java.util.function.Consumer
	at
com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1308)
	at
com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1426)
	at
com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:520)
	at
com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:798)
	at
com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:308)
	at
com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)
	at
com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3742)
	at
com.cradleVSA.neptune.database.DatabaseTypeConverters.fromStringList(DatabaseTypeConverters.kt:42)
	at
com.cradleVSA.neptune.database.daos.ReadingDao_Impl$1.bind(ReadingDao_Impl.java:127)
	at
com.cradleVSA.neptune.database.daos.ReadingDao_Impl$1.bind(ReadingDao_Impl.java:64)
	at
androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:63)
	at
com.cradleVSA.neptune.database.daos.ReadingDao_Impl$9.call(ReadingDao_Impl.java:290)
	at
com.cradleVSA.neptune.database.daos.ReadingDao_Impl$9.call(ReadingDao_Impl.java:285)
	at
androidx.room.CoroutinesRoom$Companion.execute(CoroutinesRoom.kt:53)
	at androidx.room.CoroutinesRoom.execute(CoroutinesRoom.kt)
	at
com.cradleVSA.neptune.database.daos.ReadingDao_Impl.insert(ReadingDao_Impl.java:285)
	at
com.cradleVSA.neptune.manager.PatientManager$addPatientWithReading$2.invokeSuspend(PatientManager.kt:57)
	at
com.cradleVSA.neptune.manager.PatientManager$addPatientWithReading$2.invoke(PatientManager.kt)
	at
androidx.room.RoomDatabaseKt$withTransaction$2.invokeSuspend(RoomDatabase.kt:58)
	at
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at
kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at
kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at
kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at
kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown
Source)
	at
androidx.room.RoomDatabaseKt$acquireTransactionThread$$inlined$suspendCancellableCoroutine$lambda$2.run(RoomDatabase.kt:121)
	at
androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:47)
	at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalArgumentException: Failed on call to
`getDeclaredMethods()` on class `kotlin.collections.EmptyList`, problem:
(java.lang.NoClassDefFoundError) java.util.function.Consumer
	at
com.fasterxml.jackson.databind.util.ClassUtil._failGetClassMethods(ClassUtil.java:1244)
	at
com.fasterxml.jackson.databind.util.ClassUtil.getClassMethods(ClassUtil.java:1233)
	at
com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector._addMemberMethods(AnnotatedMethodCollector.java:117)
	at
com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector.collect(AnnotatedMethodCollector.java:49)
	at
com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector.collectMethods(AnnotatedMethodCollector.java:40)
	at
com.fasterxml.jackson.databind.introspect.AnnotatedClass._methods(AnnotatedClass.java:387)
	at
com.fasterxml.jackson.databind.introspect.AnnotatedClass.memberMethods(AnnotatedClass.java:327)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesColle