attempt updates for user's security provider
Without this, older, outdated Android devices will not be able to
connect to the (staging) server due to their outdated TLS version
causing SSLHandshakeExceptions from unsupported protocol errors.

Logcat errors:

    E/HTTP POST https://cmpt373-lockdown.cs.surrey.sfu.ca/api/user/auth
     - Exception
    E/HTTP javax.net.ssl.SSLHandshakeException:
      javax.net.ssl.SSLProtocolException: SSL handshake aborted:
      ssl=0x62952cf8: Failure in SSL library, usually a protocol error
    E/HTTP error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:
      unsupported protocol (external/openssl/ssl/s23_clnt.c:714
      0x5fa9edf4:0x00000000)

Later on, after successful upgrade:

    D/LoginActivity(17613): attempting to run ProviderInstaller
    W/ProviderInstaller(17613): Failed to load providerinstaller module:
     No acceptable module found. Local version is 0 and remote version
     is 0.
    I/ProviderInstaller(17613): Installed default security provider
     GmsCore_OpenSSL
    I/HTTP: POST https://cmpt373-lockdown.cs.surrey.sfu.ca/api/user/auth
     - Success 200
    I/HTTP: GET https://cmpt373-lockdown.cs.surrey.sfu.ca/api/patients
     - Success 200
    I/HTTP : GET
    https://cmpt373-lockdown.cs.surrey.sfu.ca/api/facilities - Success 200